import datetime as dt
z=dt.datetime.now()
print(z)
print(z.year)
print(z.strftime("%a"))
print(z.strftime("%A"))
print(z.strftime("%b"))
print(z.strftime("%B"))
print(z.strftime("%c"))
print(z.strftime("%C"))
print(z.strftime("%H"))
print(z.strftime("%I"))
x=dt.datetime(2021,3,18)
print("Today's date is",x)
